#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpenWeather.Droid.Resource", IsApplication=true)]

namespace OpenWeather.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::OpenWeather.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::OpenWeather.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::OpenWeather.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::OpenWeather.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::OpenWeather.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::OpenWeather.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::OpenWeather.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::OpenWeather.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::OpenWeather.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::OpenWeather.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::OpenWeather.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::OpenWeather.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::OpenWeather.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::OpenWeather.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::OpenWeather.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::OpenWeather.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::OpenWeather.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::OpenWeather.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::OpenWeather.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::OpenWeather.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::OpenWeather.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010042
			public const int MvxBind = 2130772034;
			
			// aapt resource value: 0x7f010046
			public const int MvxDropDownItemTemplate = 2130772038;
			
			// aapt resource value: 0x7f010047
			public const int MvxGroupItemTemplate = 2130772039;
			
			// aapt resource value: 0x7f010045
			public const int MvxItemTemplate = 2130772037;
			
			// aapt resource value: 0x7f010043
			public const int MvxLang = 2130772035;
			
			// aapt resource value: 0x7f010048
			public const int MvxSource = 2130772040;
			
			// aapt resource value: 0x7f010044
			public const int MvxTemplate = 2130772036;
			
			// aapt resource value: 0x7f010000
			public const int barrierAllowsGoneWidgets = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int barrierDirection = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int chainUseRtl = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int constraintSet = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int constraint_referenced_ids = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int content = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int emptyVisibility = 2130771974;
			
			// aapt resource value: 0x7f010040
			public const int font = 2130772032;
			
			// aapt resource value: 0x7f010039
			public const int fontProviderAuthority = 2130772025;
			
			// aapt resource value: 0x7f01003c
			public const int fontProviderCerts = 2130772028;
			
			// aapt resource value: 0x7f01003d
			public const int fontProviderFetchStrategy = 2130772029;
			
			// aapt resource value: 0x7f01003e
			public const int fontProviderFetchTimeout = 2130772030;
			
			// aapt resource value: 0x7f01003a
			public const int fontProviderPackage = 2130772026;
			
			// aapt resource value: 0x7f01003b
			public const int fontProviderQuery = 2130772027;
			
			// aapt resource value: 0x7f01003f
			public const int fontStyle = 2130772031;
			
			// aapt resource value: 0x7f010041
			public const int fontWeight = 2130772033;
			
			// aapt resource value: 0x7f010007
			public const int layout_constrainedHeight = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_constrainedWidth = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_constraintBaseline_creator = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int layout_constraintBaseline_toBaselineOf = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_constraintBottom_creator = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_constraintBottom_toBottomOf = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_constraintBottom_toTopOf = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int layout_constraintCircle = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int layout_constraintCircleAngle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int layout_constraintCircleRadius = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int layout_constraintDimensionRatio = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int layout_constraintEnd_toEndOf = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int layout_constraintEnd_toStartOf = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int layout_constraintGuide_begin = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int layout_constraintGuide_end = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int layout_constraintGuide_percent = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int layout_constraintHeight_default = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int layout_constraintHeight_max = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int layout_constraintHeight_min = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int layout_constraintHeight_percent = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int layout_constraintHorizontal_bias = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int layout_constraintHorizontal_chainStyle = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int layout_constraintHorizontal_weight = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int layout_constraintLeft_creator = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int layout_constraintLeft_toLeftOf = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int layout_constraintLeft_toRightOf = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int layout_constraintRight_creator = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int layout_constraintRight_toLeftOf = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int layout_constraintRight_toRightOf = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int layout_constraintStart_toEndOf = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int layout_constraintStart_toStartOf = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int layout_constraintTop_creator = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int layout_constraintTop_toBottomOf = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int layout_constraintTop_toTopOf = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int layout_constraintVertical_bias = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int layout_constraintVertical_chainStyle = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int layout_constraintVertical_weight = 2130772011;
			
			// aapt resource value: 0x7f01002c
			public const int layout_constraintWidth_default = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int layout_constraintWidth_max = 2130772013;
			
			// aapt resource value: 0x7f01002e
			public const int layout_constraintWidth_min = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int layout_constraintWidth_percent = 2130772015;
			
			// aapt resource value: 0x7f010030
			public const int layout_editor_absoluteX = 2130772016;
			
			// aapt resource value: 0x7f010031
			public const int layout_editor_absoluteY = 2130772017;
			
			// aapt resource value: 0x7f010032
			public const int layout_goneMarginBottom = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int layout_goneMarginEnd = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int layout_goneMarginLeft = 2130772020;
			
			// aapt resource value: 0x7f010035
			public const int layout_goneMarginRight = 2130772021;
			
			// aapt resource value: 0x7f010036
			public const int layout_goneMarginStart = 2130772022;
			
			// aapt resource value: 0x7f010037
			public const int layout_goneMarginTop = 2130772023;
			
			// aapt resource value: 0x7f010038
			public const int layout_optimizationLevel = 2130772024;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f050000
			public const int abc_action_bar_embed_tabs = 2131034112;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070007
			public const int buttonColour = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int colorAccent = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int colorPrimaryDark = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int colorPrimaryOrange = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int notification_action_color_filter = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int notification_icon_bg_color = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ripple_material_light = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int secondary_text_default_material_light = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int white = 2131165192;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060004
			public const int compat_button_inset_horizontal_material = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int compat_button_inset_vertical_material = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int compat_button_padding_horizontal_material = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int compat_button_padding_vertical_material = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int compat_control_corner_material = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int notification_action_icon_size = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int notification_action_text_size = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int notification_big_circle_margin = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int notification_content_margin_start = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int notification_large_icon_height = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int notification_large_icon_width = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int notification_main_column_padding_top = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int notification_media_narrow_margin = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int notification_right_icon_size = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int notification_right_side_padding_top = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int notification_small_icon_background_padding = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int notification_small_icon_size_as_large = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int notification_subtext_size = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int notification_top_pad = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int notification_top_pad_large_text = 2131099667;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090006
			public const int MvvmCrossTagId = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int MvxBindingTagUnique = 2131296263;
			
			// aapt resource value: 0x7f090023
			public const int action_container = 2131296291;
			
			// aapt resource value: 0x7f09002f
			public const int action_divider = 2131296303;
			
			// aapt resource value: 0x7f090024
			public const int action_image = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int action_text = 2131296293;
			
			// aapt resource value: 0x7f090030
			public const int actions = 2131296304;
			
			// aapt resource value: 0x7f09001c
			public const int async = 2131296284;
			
			// aapt resource value: 0x7f090016
			public const int barrier = 2131296278;
			
			// aapt resource value: 0x7f09001d
			public const int blocking = 2131296285;
			
			// aapt resource value: 0x7f090008
			public const int bottom = 2131296264;
			
			// aapt resource value: 0x7f090017
			public const int chains = 2131296279;
			
			// aapt resource value: 0x7f090035
			public const int chosenCity = 2131296309;
			
			// aapt resource value: 0x7f09002e
			public const int chronometer = 2131296302;
			
			// aapt resource value: 0x7f09003c
			public const int date = 2131296316;
			
			// aapt resource value: 0x7f090018
			public const int dimensions = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int direct = 2131296281;
			
			// aapt resource value: 0x7f090009
			public const int end = 2131296265;
			
			// aapt resource value: 0x7f09003b
			public const int forecast = 2131296315;
			
			// aapt resource value: 0x7f090021
			public const int forecastField = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int forecastValue = 2131296290;
			
			// aapt resource value: 0x7f09001e
			public const int forever = 2131296286;
			
			// aapt resource value: 0x7f090036
			public const int getWeather = 2131296310;
			
			// aapt resource value: 0x7f09000e
			public const int gone = 2131296270;
			
			// aapt resource value: 0x7f090027
			public const int icon = 2131296295;
			
			// aapt resource value: 0x7f090031
			public const int icon_group = 2131296305;
			
			// aapt resource value: 0x7f09002a
			public const int info = 2131296298;
			
			// aapt resource value: 0x7f09000f
			public const int invisible = 2131296271;
			
			// aapt resource value: 0x7f09001f
			public const int italic = 2131296287;
			
			// aapt resource value: 0x7f09000a
			public const int left = 2131296266;
			
			// aapt resource value: 0x7f090000
			public const int line1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int line3 = 2131296257;
			
			// aapt resource value: 0x7f090033
			public const int main_loader = 2131296307;
			
			// aapt resource value: 0x7f09001a
			public const int none = 2131296282;
			
			// aapt resource value: 0x7f090020
			public const int normal = 2131296288;
			
			// aapt resource value: 0x7f09002c
			public const int notification_background = 2131296300;
			
			// aapt resource value: 0x7f090028
			public const int notification_main_column = 2131296296;
			
			// aapt resource value: 0x7f090026
			public const int notification_main_column_container = 2131296294;
			
			// aapt resource value: 0x7f090014
			public const int packed = 2131296276;
			
			// aapt resource value: 0x7f090010
			public const int parent = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int percent = 2131296273;
			
			// aapt resource value: 0x7f09000b
			public const int right = 2131296267;
			
			// aapt resource value: 0x7f09002b
			public const int right_icon = 2131296299;
			
			// aapt resource value: 0x7f090029
			public const int right_side = 2131296297;
			
			// aapt resource value: 0x7f09003e
			public const int speak = 2131296318;
			
			// aapt resource value: 0x7f090032
			public const int splash_loader = 2131296306;
			
			// aapt resource value: 0x7f090012
			public const int spread = 2131296274;
			
			// aapt resource value: 0x7f090015
			public const int spread_inside = 2131296277;
			
			// aapt resource value: 0x7f09001b
			public const int standard = 2131296283;
			
			// aapt resource value: 0x7f09000c
			public const int start = 2131296268;
			
			// aapt resource value: 0x7f090002
			public const int tag_transition_group = 2131296258;
			
			// aapt resource value: 0x7f09003a
			public const int temperature = 2131296314;
			
			// aapt resource value: 0x7f090003
			public const int text = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int text2 = 2131296260;
			
			// aapt resource value: 0x7f090034
			public const int textView = 2131296308;
			
			// aapt resource value: 0x7f09002d
			public const int time = 2131296301;
			
			// aapt resource value: 0x7f090005
			public const int title = 2131296261;
			
			// aapt resource value: 0x7f09000d
			public const int top = 2131296269;
			
			// aapt resource value: 0x7f090037
			public const int voiceInput = 2131296311;
			
			// aapt resource value: 0x7f090038
			public const int weatherHeader = 2131296312;
			
			// aapt resource value: 0x7f090039
			public const int weatherIcon = 2131296313;
			
			// aapt resource value: 0x7f09003d
			public const int weatherListView = 2131296317;
			
			// aapt resource value: 0x7f090013
			public const int wrap = 2131296275;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int status_bar_notification_info_maxnum = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_adapter = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification_action = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action_tombstone = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_template_custom_big = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_template_icon_group = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_part_chronometer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_part_time = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int splash_screen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int view_main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int view_weather_details = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int status_bar_notification_info_overflow = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_Compat_Notification = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification_Info = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Line2 = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Time = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Title = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int WeatherAppNoTitle = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int WeatherAppTitle = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int Widget_Compat_NotificationActionContainer = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int Widget_Compat_NotificationActionText = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					16843039,
					16843040,
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024};
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_android_maxHeight = 2;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_android_minHeight = 4;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_barrierDirection = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_chainUseRtl = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_constraintSet = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_constraint_referenced_ids = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constrainedHeight = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constrainedWidth = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintCircle = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
			
			// aapt resource value: 37
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
			
			// aapt resource value: 38
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
			
			// aapt resource value: 39
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
			
			// aapt resource value: 40
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
			
			// aapt resource value: 41
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
			
			// aapt resource value: 42
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
			
			// aapt resource value: 43
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
			
			// aapt resource value: 44
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
			
			// aapt resource value: 45
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
			
			// aapt resource value: 46
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
			
			// aapt resource value: 47
			public const int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
			
			// aapt resource value: 48
			public const int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
			
			// aapt resource value: 49
			public const int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
			
			// aapt resource value: 50
			public const int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
			
			// aapt resource value: 51
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
			
			// aapt resource value: 52
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
			
			// aapt resource value: 53
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
			
			// aapt resource value: 54
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
			
			// aapt resource value: 55
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
			
			// aapt resource value: 56
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 56;
			
			// aapt resource value: 57
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 57;
			
			// aapt resource value: 58
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 58;
			
			// aapt resource value: 59
			public const int ConstraintLayout_Layout_layout_optimizationLevel = 59;
			
			public static int[] ConstraintLayout_placeholder = new int[] {
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int ConstraintLayout_placeholder_content = 0;
			
			// aapt resource value: 1
			public const int ConstraintLayout_placeholder_emptyVisibility = 1;
			
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843551,
					16843552,
					16843553,
					16843554,
					16843555,
					16843556,
					16843557,
					16843558,
					16843559,
					16843560,
					16843701,
					16843702,
					16843770,
					16843840,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023};
			
			// aapt resource value: 9
			public const int ConstraintSet_android_alpha = 9;
			
			// aapt resource value: 22
			public const int ConstraintSet_android_elevation = 22;
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 20
			public const int ConstraintSet_android_layout_marginEnd = 20;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 19
			public const int ConstraintSet_android_layout_marginStart = 19;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 16
			public const int ConstraintSet_android_rotation = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_android_rotationX = 17;
			
			// aapt resource value: 18
			public const int ConstraintSet_android_rotationY = 18;
			
			// aapt resource value: 14
			public const int ConstraintSet_android_scaleX = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_android_scaleY = 15;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_transformPivotX = 10;
			
			// aapt resource value: 11
			public const int ConstraintSet_android_transformPivotY = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_android_translationX = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_android_translationY = 13;
			
			// aapt resource value: 21
			public const int ConstraintSet_android_translationZ = 21;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constrainedHeight = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constrainedWidth = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintBaseline_creator = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintBottom_creator = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintCircle = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintCircleAngle = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintCircleRadius = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintDimensionRatio = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintGuide_begin = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintGuide_end = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintGuide_percent = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_constraintHeight_default = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_constraintHeight_max = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_constraintHeight_min = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_constraintHeight_percent = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_constraintHorizontal_bias = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_constraintHorizontal_chainStyle = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_constraintHorizontal_weight = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_constraintLeft_creator = 46;
			
			// aapt resource value: 47
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 47;
			
			// aapt resource value: 48
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 48;
			
			// aapt resource value: 49
			public const int ConstraintSet_layout_constraintRight_creator = 49;
			
			// aapt resource value: 50
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 50;
			
			// aapt resource value: 51
			public const int ConstraintSet_layout_constraintRight_toRightOf = 51;
			
			// aapt resource value: 52
			public const int ConstraintSet_layout_constraintStart_toEndOf = 52;
			
			// aapt resource value: 53
			public const int ConstraintSet_layout_constraintStart_toStartOf = 53;
			
			// aapt resource value: 54
			public const int ConstraintSet_layout_constraintTop_creator = 54;
			
			// aapt resource value: 55
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 55;
			
			// aapt resource value: 56
			public const int ConstraintSet_layout_constraintTop_toTopOf = 56;
			
			// aapt resource value: 57
			public const int ConstraintSet_layout_constraintVertical_bias = 57;
			
			// aapt resource value: 58
			public const int ConstraintSet_layout_constraintVertical_chainStyle = 58;
			
			// aapt resource value: 59
			public const int ConstraintSet_layout_constraintVertical_weight = 59;
			
			// aapt resource value: 60
			public const int ConstraintSet_layout_constraintWidth_default = 60;
			
			// aapt resource value: 61
			public const int ConstraintSet_layout_constraintWidth_max = 61;
			
			// aapt resource value: 62
			public const int ConstraintSet_layout_constraintWidth_min = 62;
			
			// aapt resource value: 63
			public const int ConstraintSet_layout_constraintWidth_percent = 63;
			
			// aapt resource value: 64
			public const int ConstraintSet_layout_editor_absoluteX = 64;
			
			// aapt resource value: 65
			public const int ConstraintSet_layout_editor_absoluteY = 65;
			
			// aapt resource value: 66
			public const int ConstraintSet_layout_goneMarginBottom = 66;
			
			// aapt resource value: 67
			public const int ConstraintSet_layout_goneMarginEnd = 67;
			
			// aapt resource value: 68
			public const int ConstraintSet_layout_goneMarginLeft = 68;
			
			// aapt resource value: 69
			public const int ConstraintSet_layout_goneMarginRight = 69;
			
			// aapt resource value: 70
			public const int ConstraintSet_layout_goneMarginStart = 70;
			
			// aapt resource value: 71
			public const int ConstraintSet_layout_goneMarginTop = 71;
			
			public static int[] FontFamily = new int[] {
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130772031,
					2130772032,
					2130772033};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			public static int[] MvxBinding = new int[] {
					2130772034,
					2130772035};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130772036};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130772039};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130772040};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130772037,
					2130772038};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
